### ISSUE TITLE
[bug] KeepAliveSender keeps waiting after message pipe closed

### ISSUE THREAD

**Issue by Calrama** [WhisperSystems/libsignal-service-java#13]
The KeepAliveSender instance for a TextSecureMessagePipe will keep waiting [here](https://github.com/WhisperSystems/libtextsecure-java/blob/4c93231c3ccfb662d42c52348b7ad1ad9f3989a4/java/src/main/java/org/whispersystems/textsecure/internal/websocket/WebSocketConnection.java#L163) for its specified delay (default: 55 seconds) after the pipe has been closed with `shutdown()`. This potentially keeps an application that should close running for at most that delay.

**Steps to reproduce**:

``` Java
TextSecureMessageReceiver receiver = [...]
TextSecureMessagePipe pipe = receiver.createMessagePipe()
pipe.shutdown()
```

**Possible solutions**:
- Make keepAliveSender be a daemon thread with `keepAliveSender.setDaemon(true)`.
- Interrupt the keepAliveSender instance in [`shutdown()`](https://github.com/WhisperSystems/libtextsecure-java/blob/4c93231c3ccfb662d42c52348b7ad1ad9f3989a4/java/src/main/java/org/whispersystems/textsecure/internal/websocket/WebSocketConnection.java#L173) and disregard the resulting exception

**Comment by moxie0** [comment]
Thanks for the report but I'm fine with the current behavior.
