### ISSUE TITLE
Most phone numbers lost link to contacts after update to Signal 3.25.0

### ISSUE THREAD

**Issue by cryptomilk** [WhisperSystems/libsignal-service-java#29]
After the update to Signal 3.25.0 most of my conversation show just the phone number and not the name anymore. I think this is because of the update of libphonenumber.

The strange thing is phone number are displayed differently:

+49 173 xxxxxxx
+49176xxxxxxxx
+49 176 xxxxxxxx

Why do some number have spaces an others don't?

I'm running Android 7.1.1 (CyanogenMod 14.1). Let me know if I can provide more details.

**Comment by cryptomilk** [comment]
https://github.com/googlei18n/libphonenumber/issues/1443

**Comment by moxie0** [comment]
Hmm, are the numbers displayed correct?

**Comment by moxie0** [comment]
Also when you open a conversation with a contact that is displayed only as a number, is the conversation history from pre-3.25.0 there? Can you post a debug log?

**Comment by moxie0** [comment]
Also can you move this issue over to the Signal-Android repo? Easier to track that this is blocking release there.

**Comment by cryptomilk** [comment]
The number with 10 digits seem to be rendered correctly, the ones with 11 aren't. The history from pre-3.25.0 conversations are intact. I've opened a bug in the Signal-Android repo here:

https://github.com/WhisperSystems/Signal-Android/issues/5974

I will attach a log later.

**Comment by cryptomilk** [comment]
FYI: libphonenumber 8.0.1 has been released with fixes for German phone numbers.
