### ISSUE TITLE
Don't and drive

### ISSUE THREAD

**Issue by PIXELSTURM** [WhisperSystems/libsignal-service-java#32]
After the last update hours ago, the desktop workabilities on OSX has gone. WTF? Kindergarden? Is it so hard to »prog« for »multiplatforms«? Hey, it's fucking java, isn't it??? I'am really pissed off. Take a look at the title, thanks!

**Comment by Trolldemorted** [comment]
No, its not java. And libsignal-service-java is not intended to be run anywhere except android.

If your Signal-Desktop fails, you should complain there.
