### ISSUE TITLE
Issue on implementing lib

### ISSUE THREAD

**Issue by viswakarmalovekush** [WhisperSystems/libsignal-service-java#35]
Error:(65, 0) Could not get unknown property 'sonatypeRepo' for project ':android' of type org.gradle.api.Project.
<a href="openFile:/Users/lovekushvishwakarma/Documents/TagTeenApp/TagTeenChat/android_chat/build.gradle">Open File</a>

there is not proper guideline for implementation or no any demo with lib... please help

**Comment by Turakar** [comment]
Did you use the gradle wrapper using `./gradle build`? This could happen on Linux systems.

**Comment by moxie0** [comment]
hey @viswakarmalovekush we don't use the issue tracker for support, discussion, or q&a. try the online forums for discussion, or the support center for support. thanks!
