### ISSUE TITLE
Library issue related to versiion

### ISSUE THREAD

**Issue by viswakarmalovekush** [WhisperSystems/libsignal-service-java#38]
I am trying to use wishoerSystem lib for chat, when I am using this
compile 'org.whispersystems:libsignal-service-android:2.5.4'
I am getting error like this lib cannot resolved.
but when I am using this 
 compile 'org.whispersystems:signal-service-android:2.5.3'
it is accepted by cradle ...
so which one is correct?

**Comment by p4nci** [comment]
@viswakarmalovekush there is no libsignal-service-android:2.5.4
you can use v2.5.3 or latest one v2.5.5

@moxie0 was that indented? (see https://github.com/WhisperSystems/libsignal-service-java/commit/2154ae4c5ced0b81699935efc8c36a0176b03811)

**Comment by moxie0** [comment]
it was intended
