### ISSUE TITLE
Poor user guide 

### ISSUE THREAD

**Issue by viswakarmalovekush** [WhisperSystems/libsignal-service-java#39]
IdentityKeyPair    identityKey        = KeyHelper.generateIdentityKeyPair();
List<PreKeyRecord> oneTimePreKeys     = KeyHelper.generatePreKeys(0, 100);
PreKeyRecord       lastResortKey      = KeyHelper.generateLastResortPreKey();
SignedPreKeyRecord signedPreKeyRecord = KeyHelper.generateSignedPreKey(identityKey, signedPreKeyId);

in this how to get signedPreKeyId?

**Comment by moxie0** [comment]
hey @viswakarmalovekush we try not to use the github issues for support, q&a, or discussion.  For discussion please see the online forums, for support please see the support center. Thanks!
