### ISSUE TITLE
A better example/tutorial

### ISSUE THREAD

**Issue by der-Daniel** [WhisperSystems/libsignal-service-java#44]
Hello,

I really wanted to build an app/bot upon the signal messenger.
Is there a better example set/tutorial on the API then the readme, or plans on adding such a thing?

For Frodo

**Comment by Trolldemorted** [comment]
This is a question for the community forum or the mailing list, but not the issue tracker.

https://whispersystems.discoursehosting.net/t/libsignal-service-java-simple-usage-example/1177
